gendef: build with -Wno-implicit-fallthrough
gcc 7 has -Wimplicit-fallthrough on by default. On systems where the
build gcc is v7 or newer building gendef will therefore fail with the
following error:

src/gendef.c: In function ‘getMemonic’:
src/gendef.c:1034:15: error: this statement may fall through [-Werror=implicit-fallthrough=]
   case c_4: sz++;

Fixes #1786.