plugins/examples/qt5-freeze: Fix qtimageformats build (fixes #2563).
Add missing <math.h> #include. Without this the build fails with:

 [...]qjp2handler.cpp:853:86: error: 'pow' was not declared in this scope

Taken from bd76e1080ef7ddbbfe683d6371629aecb02bc9bd.