ghostscript v10.01.1
Ghostscript needs pread() and pwrite() to use tesseract, so it has to be disabled.

The test binary fails to build with -pedantic:
include/ghostscript/iapi.h:395:27: error: enumerator value for 'gs_spt_more_to_come' is not an integer constant expression [-Werror=pedantic]