Add libraw: library for processing raw image files
Let's keep jasper disabled for now, as it produces build errors:

    /mnt/Lavoro/mxe/mxe/usr/x86_64-w64-mingw32.shared/include/jasper/jas_math.h:
    In function 'bool jas_safe_intfast32_mul(int_fast32_t, int_fast32_t,
                                             int_fast32_t*)':
    /mnt/Lavoro/mxe/mxe/usr/x86_64-w64-mingw32.shared/include/jasper/jas_math.h:241:12:
    error: 'INT_FAST32_MAX' was not declared in this scope
        if (x > INT_FAST32_MAX / y) {
                        ^

It's not a required dependency, but we might want to add it later if
someone asks for it (and can provide a solution).