fontconfig: update from 2.12.3 to 2.12.4
This fixes compilation with gcc >= 6. Actual error message:

```
In file included from fcobjs.c:33:0:
fcobjshash.gperf:172:1: error: conflicting types for 'FcObjectTypeLookup'
```