log4cxx: fix invalid narrowing conversion tripping up g++ >= 6
g++ 6 is stricter regarding narrowing conversions in initializer
lists. This causes errors similar to the following during compilation
with the gcc6 or gcc7 overlays:

    locationinfo.cpp:163:21: error: narrowing conversion of '237'
    from 'int' to 'char' inside { } [-Wnarrowing]

This has already been fixed upstream in several consecutive patches,
but there's no release including those fixes yet. This patch consists
of the essence of said fixes.