go plugin: fix build on darwin
build fails with:

```
fatal error: runtime: bsdthread_register error (unset DYLD_INSERT_LIBRARIES)
```

building with `-ldflags -linkmode=external`[1] and `CGO_ENABLED=1` has no
affect on `go-native`, it does let `go` bootstrap, but then fails with a
similar error:

```
fatal error: runtime: bsdthread_register error
```

easiest to unset DYLD_INSERT_LIBRARIES - no need to check for `darwin` as it
only exists on that platform.

[1] https://github.com/golang/go/issues/8801#issuecomment-66460009