qt4 build fix
Previously failed with
    kernel/qapplication_win.cpp:2638:13: error: 'GESTUREINFO' was not declared in this scope

GESTUREINFO is defined in winuser.h and requires WINVER >= 0x0601
(Windows 7).

https://github.com/mxe/mxe/issues/3034