Build the graphviz libraries, most plugins and application (notably 'dot').
NOTES (also available in the new src/graphviz.mk):

* Before using graphviz (application or library), a configration file
  called 'config6' must be created in the directory that also contains the
  libraries. This can be achieved by running 'dot -c', where dot is the
  cross-compiled dot program. Note that this requires write privileges in the
  MXE-installation directory. This can also be achieved on the build system
  by invoking 'wine /path/to/mxe/targetdir/bin/dot -c'. (This is not done as
  part of this Makefile, since Wine cannot be used (see 'do not run target
  executables with Wine' on https://mxe.cc/).

* mman-win32 has been made a dependency and we make sure that the mman library
  is linked in by passing LIBS=-lmman to configure. This library is needed for
  the mmap and munmap functions. At present, graphviz' configure script only
  checks for the availability of <sys/mman.h>. When found (as for MXE builds),
  it defines HAVE_SYS_MMAN_H in config.h and erroneously assumes that these
  functions are available in the C library. Linking against -lmman fixes this
  problem.

* At present, --disable-qt is passed to the graphviz configure script.
  Enabling qt requires that CXXFLAGS=-fpermissive is passed to configure
  to prevent the following compilation error:

       ../../../cmd/gvedit/csettings.cpp: In function 'QString findAttrFile()':
       ../../../cmd/gvedit/csettings.cpp:43:23: error: invalid conversion from
       'QString (*)()' to 'LPCVOID' {aka 'const void*'} [-fpermissive]
       43 |     if (VirtualQuery (&findAttrFile, &mbi, sizeof(mbi)) == 0) {
          |                       ^~~~~~~~~~~~~
          |                       |
          |                       QString (*)()

  When enabling qt support, qt (or just qt-base?) should also be added to the
  $(PKG)_DEPS variable below.

* At present, --disable-perl is passed to the graphviz configure script.
  On an OpenSUSE Tumbleweed test system, enabling perl results in the
  inclusion of /usr/lib/perl5/5.34.1/x86_64-linux-thread-multi/CORE/perl.h,
  which includes <sys/wait.h>. Since this file is not available for MXE builds,
  this results in a compilation error. This requires somebody with a better
  understanding of Perl.